# Generated by Django 4.1.7 on 2023-03-31 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkablePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название места')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Примечательное место',
                'verbose_name_plural': 'Примечательные места',
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_c', models.CharField(max_length=50, verbose_name='Температура')),
                ('humidity', models.CharField(max_length=50, verbose_name='Влажность')),
                ('pressure_mb', models.CharField(max_length=50, verbose_name='Давление')),
                ('wind_dir', models.CharField(max_length=50, verbose_name='Направление ветра')),
                ('wind_kph', models.CharField(max_length=50, verbose_name='Скорость ветра')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время измерений')),
                ('remarkable_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remarkable_place_app.remarkableplaces')),
            ],
            options={
                'verbose_name': 'Сводка погоды',
                'verbose_name_plural': 'Сводка погоды',
            },
        ),
    ]
