# Generated by Django 4.1.7 on 2023-03-31 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('publication_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата новости')),
                ('author', models.CharField(max_length=255, verbose_name='Автор новости')),
                ('image', models.ImageField(upload_to='news/%Y-%m-%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
